services:
  postgres:
    image: postgres
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_DB: twithive
      POSTGRES_USER: twithive
      POSTGRES_PASSWORD: twithive@99

